spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/chattrix

  jpa:
    hibernate:
      ddl-auto: update

  mongodb:
    uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@localhost/ChatData?authSource=admin