spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mariadb://db:3306/chattrix
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update