spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

  mongodb:
    uri: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/ChatData?authSource=admin