services:
  db:
    image: mariadb:jammy
    container_name: chattrix-db
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - chattrix-mysql-local-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chattrix-phpmyadmin
    restart: always

    environment:
      PMA_HOST: localhost
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8090:80"

    depends_on:
      - db

volumes:
  chattrix-mysql-local-data: