services:
  db:
    image: mariadb:jammy
    container_name: chattrix-db
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - chattrix-mysql-production-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo
    container_name: chattrix-mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}

  chattrix-backend:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile

    image: chattrix-backend:latest

    container_name: chattrix-backend
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/chattrix
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    depends_on:
      db:
        condition: service_healthy

volumes:
  chattrix-mysql-production-data: