spring.application.name=chat-service

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.mongodb.host=${MONGODB_HOST}
spring.mongodb.port=${MONGODB_PORT}
spring.mongodb.database=${MONGODB_DATABASE}
spring.mongodb.username=${MONGO_ROOT_USER}
spring.mongodb.password=${MONGO_ROOT_PASSWORD}
spring.mongodb.authentication-database=admin

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2000ms