spring.application.name=chat-service
server.port=8082
spring.data.mongodb.uri=mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=chat_service
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2000ms